### ISSUE TITLE
compilerOptions.paths not relative to ts config file on extends

### ISSUE THREAD

**Issue by Chocobozzz** [benyap/resolve-tspaths#10]
Hi,

resolve-tspaths correctly handles tsconfig `extends`, but does not resolve `compilerOptions.paths` from tsconfig where it was defined. It means that `paths` are resolved from the main tsconfig file resulting in invalid path resolution.

**Comment by benyap** [comment]
Thanks for the issue @Chocobozzz. Could you provide a bit more detail, such as what the current behaviour is vs the expected behaviour?

**Comment by Chocobozzz** [comment]
Sure!

We have a [tsconfig file](https://github.com/Chocobozzz/PeerTube/blob/develop/server/tools/tsconfig.json) defined in `server/tools` directory extending [another one](https://github.com/Chocobozzz/PeerTube/blob/develop/tsconfig.json) that is at the root of the repository. The parent tsconfig defines `paths`: https://github.com/Chocobozzz/PeerTube/blob/develop/tsconfig.json#L7. The `server/tools` tsconfig also defines paths because of this bug, but it should not.

resolve-tspaths correctly merge these tsconfig files, but then resolve `paths` property paths from `server/tools`. Since the `paths` property were defined in the root tsconfig, they should be resolved from the root of the repository.

**Comment by benyap** [comment]
I see, that makes sense. Will look into this and hopefully have a fix soon :)

**Comment by benyap** [comment]
@all-contributors add @Chocobozzz for bug report
