### ISSUE TITLE
Add support for `require.resolve`

### ISSUE THREAD

**Issue by wintercounter** [benyap/resolve-tspaths#119]
I'm using aliases in `require.resolve` statements. Previously I was using a Babel plugin to resolve my paths, but I switched to SWC and now I'd like to use your package to fix paths after compilation. However, `require.resolve` is not supported.

**Comment by benyap** [comment]
Hey @wintercounter, this has been released in [v0.7.0](https://github.com/benyap/resolve-tspaths/releases/tag/v0.7.0). Please give it a shot and let me know if you have any feedback! Thanks for using this package and giving the suggestion :)
