### ISSUE TITLE
Broken replacement when export and file contain the same string

### ISSUE THREAD

**Issue by Zebreus** [benyap/resolve-tspaths#151]
When the exported symbol contains the same string as the filename, the symbol gets replaced instead of the filename. This probably only affects projects that use no prefix for their aliases.

## Example:
tsconfig.json:
```json
{ "compilerOptions": {
      "paths": {
        "*": ["./src/*"]
      }
}}
```

src/sameName.ts:
```typescript
export const sameName = "something"
```

src/test.ts:
```typescript
export { sameName } from "sameName"
```
### Expected behaviour

The generated `test.d.ts` contains
```typescript
export { sameName } from "./sameName"
```

### Actual behaviour

The generated `test.d.ts` contains
```typescript
export { ./sameName } from "sameName"
```

**Comment by benyap** [comment]
Fix released in [v0.7.5](https://github.com/benyap/resolve-tspaths/releases/tag/v0.7.5)
