### ISSUE TITLE
Add support for `extends` in tsconfig.json

### ISSUE THREAD

**Issue by ylc395** [benyap/resolve-tspaths#172]
It seems that `extends` field in tsconfig.json is not supported. Any plan for it?

**Comment by benyap** [comment]
Hi @ylc395, `extends` is supported in tsconfig.json as far as I'm aware - in fact, it is used by this project in `tsconfig.build.json` as a part of the `build` script in `package.json`.

If this is not working for you, could you please provide a working example?
