### ISSUE TITLE
Feature Request: Resolve Import Paths for TypeScript Files

### ISSUE THREAD

**Issue by alabsi91** [benyap/resolve-tspaths#216]
Currently, `resolve-tspaths` resolves import paths for compiled JavaScript files, resulting in import paths with an extension E.g. `.js`. However, it would be helpful to also resolve import paths for TypeScript files (`.ts` and `.tsx`). 
This feature would be particularly useful for libraries designed for use with `react-native`.  

```js
// package.json
{
  "main": "lib/commonjs/index",
  "module": "lib/module/index",
  "types": "lib/typescript/index.d.ts",
  "source": "lib/src/index", 👈
  "react-native": "lib/src/index"  👈
}
```
- For example in the build script, I can copy the TypeScript source code and then resolve its paths.
- To achieve this, I tried to resolve TypeScript files using the following : 
```js
await resolveTsPaths({ out: outPath, ext: ['ts', 'tsx'] });
```
- The current behavior is that import paths are resolved with a `.js` extension, which can result in a runtime error:
```js
import { styles } from '../../styles.js';
```

**Comment by alabsi91** [comment]
I have a TypeScript project that uses import aliases. I want to create another version of the project that does not use aliases, For this, I need a tool like 'resolve-tspaths' that can replace the aliases with the actual paths in the TypeScript files. However, 'resolve-tspaths' only works for JavaScript files and adds a '.js' extension to the resolved paths. This breaks the TypeScript project and prevents me from having two versions: one with aliases and one without. Is there a way to fix this or use another tool?"

**Comment by benyap** [comment]
Hey @alabsi91, could you please provide a sample repo that I can run? I need to see your files and configuration.

As I mentioned, the only reason why an import path will have `.js` appended to it by `resolve-tspaths` is if the original path had a `.ts` extension. So if you're getting `.js` added to your paths, either your paths had a `.ts` extension, or there's a bug in this package - I don't know which one it is and won't be able to assist unless you can give me more information.
