### ISSUE TITLE
Path mappings to files resolve incorrectly

### ISSUE THREAD

**Issue by jneuendorf-i4h** [benyap/resolve-tspaths#253]
Hi,

thanks for your package. It's a shame `tsc` doesn't compile its resolution behavior.

### Scenario

In my scenario, I generated JSON files from my TypeScript code (JSON schema from types).
In order to avoid import errors, I configured my path mappings so that JSON are preferred over source files:

```json
{
  "compilerOptions": {
    "rootDir": "src/",
    "baseUrl": "src/",
    "outDir": "dist/",
    "paths": {
      "~/*": ["./*"],
      "@schema/*": ["./schema/*.json", "./schema/*"],
    },
  }
}
```

The files are structured like this:

```
src/schema/
├── a.json
└── a.ts
```

and an import like this: `import { definitions } from "@schema/a"`.

### Expected behavior

This setup works fine with TypeScript. Since I think this package aims to mimic TypeScript's resolution mechanism, just at compile time, I think, this setup should also work with your package.

### Actual behavior

The JSON file is not resolved. Instead the compiled JS file is resolved.

At first I thought, the reason is that I used `--ext` incorrectly. But after some debugging, I found that the import is resolved to `.../src/schema/*.json/a` and then disregarded. This result is produced by https://github.com/benyap/resolve-tspaths/blob/main/src/steps/generateChanges.ts#L143

```typescript
resolve(aliasPath, importSpecifier.replace(prefix, ""))
```

In my understand, this code assumes that all `aliasPaths` are pointing to directories, which is not necessarily true (as described above). I guess replacing `"*"` in the path instead of appending to it (in case the alias is not a directory), could solve this issue.

```typescript
(aliasPath) => isDirectory(aliasPath)
    ? resolve(aliasPath, importSpecifier.replace(prefix, ""))
    : aliasPath.replace("*", importSpecifier.replace(prefix, ""))
```

Let me know what you think. 😉

**Comment by benyap** [comment]
Hi @jneuendorf-i4h, thanks for your issue and presenting it very clearly!

Normally, I would import a JSON file using the `.json` to differentiate it from a module:
```ts
import { ... } from "@schema/a.json";
// vs
import { ... } from "@schema/a";
```


I wasn't even aware that you could import a JSON file without using a `.json` extension 😂 but I tested it and you are right, the Typescript language server seems to be happy with importing a JSON file without `.json` if you have `"./schema/*.json"` as a path mapping.

I will note that if you don't have `"...*.json"` in the path mapping, you **cannot** import a JSON file without the `.json` extension. As you pointed out, it looks like Typescript uses `*` as a wildcard to match directories and files.

I can take a deeper look into your suggestion when I have time - or feel free to open a PR. Initial thoughts are that it looks like it could work, though it will need to be tested thoroughly.

In the interim, is there a reason why you can't import the file with a `.json` extension? `resolve-tspaths` will map your paths correctly if you simply do that 😉

**Comment by jneuendorf-i4h** [comment]
Hey @benyap, thanks for the quick reply.

I actually ended up, importing the JSON files explicitly (so like `import ... from "./a.json"`). Therefore, I am not relying on the requested behavior anymore.

You mentioned that such a feature would need to be well tested and I agree. So if the requested behavior is a bit exotic (and most users don't need it), it may not be worth increasing the complexity of the project. However, it would be helpful to state this caveat<sup>1</sup> in the README so people know what they're up to.

---

<sup>1</sup> meaning that only file paths can be correctly resolved

**Comment by benyap** [comment]
Thanks @jneuendorf-i4h for the suggestion, will update the README!

**Comment by benyap** [comment]
@all-contributors add @jneuendorf-i4h for documentation
