### ISSUE TITLE
Doesn't replace import in ESM mode with nodenext module resolution for `.d.ts` files

### ISSUE THREAD

**Issue by Chocobozzz** [benyap/resolve-tspaths#295]
Hi :)

Thanks again for the tool, very useful in our project.
There is one issue with `.d.ts` generated files when we use `"module": "NodeNext"` with `"moduleResolution": "NodeNext"` in ts config (recommended module resolution in ESM mode).

Also consider the following `paths` value:

```
...
"paths": {
      "@server/*": [ "../../../server/*" ]
} 
...
```

With `NodeNext` module resolution, `.js` extension is mandatory in ts source file:

```ts
export * from '@server/types/index.js'
export * from '@server/types/models/index.js'
```

Generated file  `dist/index.d.ts` also contains the extension:

```ts
export * from '@server/types/index.js';
export * from '@server/types/models/index.js';
```

And so imports are not updated in `dist/index.d.ts`, because `resolve-tspaths` tries to find `[filename].js.d.ts` and not `[filename].d.ts`.

([your test](https://github.com/benyap/resolve-tspaths/blob/main/test/fixtures/esModuleExtensions/tsconfig.json#L7) uses the `node` module resolution which correctly works as we don't have to specify the file extension)

**Comment by benyap** [comment]
Hi @Chocobozzz, just wanted to reach out and let you know that I've been quite busy and haven't had time to look closely into this yet. However, if you have a working solution that you could submit as a PR, I'd be happy to review it and merge it in!

**Comment by NikolaRHristov** [comment]
Hello, @Chocobozzz.

We're working to fix this in `@playform/resolve` https://github.com/Playform/Resolve. You can follow the progress there.
