### ISSUE TITLE
Watch Mode

### ISSUE THREAD

**Issue by riungemaina** [benyap/resolve-tspaths#308]
Is there a way to run this in watch mode?

**Comment by benyap** [comment]
Hi @riungemaina,

There is currently no way to run `resolve-tspaths` in watch mode. There are also no plans to add this feature at the moment.

If you need a watch function, I would recommend that you use `resolve-tspaths` in conjunction with other popular packages that can help provide this capability, such as `nodemon`, `tsc-watch`, or `turborepo`.

Hope this helps - I'm going to close this issue for now, but feel free to continue the discussion if you need help!

**Comment by bofomike** [comment]
Hey @benyap, could you show us at least 1 working example of how to use resolve-tspaths and still be able to `watch`? 

I've tried the following but unfortunately this doesn't work: 
```
"scripts": {
  "build": "tsc && resolve-tspaths",
  "build:watch": "tsc --watch && resolve-tspaths",
}
```

**Comment by benyap** [comment]
Hey @bofomike,

Check out the documentation for [tsc-watch](https://www.npmjs.com/package/tsc-watch). There is a `--onSuccess` flag which allows you to run a custom command on a **successful** compilation - this is the method I usually use.

So your `package.json` might look something like this:
```json
{
  "scripts": {
    "build": "tsc && resolve-tspaths",
    "build:watch": "tsc-watch --onSuccess 'resolve-tspaths'"
  }
}
```

**Comment by bofomike** [comment]
> Hey @bofomike,
> 
> Check out the documentation for [tsc-watch](https://www.npmjs.com/package/tsc-watch). There is a `--onSuccess` flag which allows you to run a custom command on a **successful** compilation - this is the method I usually use.
> 
> So your `package.json` might look something like this:
> 
> ```json
> {
>   "scripts": {
>     "build": "tsc && resolve-tspaths",
>     "build:watch": "tsc-watch --onSuccess 'resolve-tspaths'"
>   }
> }
> ```

Thank you man 🤝 
Works like a charm 🤍
