### ISSUE TITLE
How do i resolve aliases with outDir acting as the new base/root

### ISSUE THREAD

**Issue by kyle-belle** [benyap/resolve-tspaths#315]
I am using yarn workspaces for my project and some of my one of my workspaces imports from other work workspaces outside its root directory.

the relevant parts of my `tsconfig` look like this:
```json
"outDir": "./build",
      "paths": {
        "@app/db": ["../db"],
        "@app/db/*": ["../db/*"],
        "@app/redis": ["../redis"],
        "@app/redis/*": ["../redis/*"],
        "@app/emitter": ["../emitter"],
        "@app/emitter/*": ["../emitter/*"],
        "@app/dayjs": ["../dayjs"],
        "@app/dayjs/*": ["../dayjs/*"],
        "@app/utils": ["../utils"],
        "@app/utils/*": ["../utils"],
        "@app/values": ["../values"],
        "@app/values/*": ["../values/*"]
      },
```
with this config it transforms:
```javascript
require("@app/redis");
```
to
```javascript
require("../../../redis"); // seems to still think outside the outDir is the root
```
I am expecting it to be:
```javascript
require("../redis"); // treating outDir (/build) as the new root
```
Currently the only package i've gotten to resolve paths as i expect is [ts-alias](https://github.com/justkey007/tsc-alias) but that has a [bug](https://github.com/justkey007/tsc-alias/issues/193) and which idk if i'll be solved soon

**Comment by benyap** [comment]
Hi @kyle-belle, could you please provide an example repository that shows your folder structure and demonstrates this issue?

**Comment by kyle-belle** [comment]
> Hi @kyle-belle, could you please provide an example repository that shows your folder structure and demonstrates this issue?

Hey there. I created the example here: https://github.com/kyle-belle/resolve-tspaths-issue-example

**Comment by benyap** [comment]
Hi @kyle-belle, apologies for the delay. I've taken a look at the example you provided.

From what I can tell, the way that your project is configured, especially in `packages/api/tsconfig.json`, is not optimal for `resolve-tspaths`. I believe one of the main issues is your `baseUrl` being several directories above the current directory. Generally speaking I've only tested this tool where the `baseUrl` is **within** the current directory.

Unfortunately I don't have a working example for you on hand as a lot of my current work where I use `resolve-tspaths` is closed-source.

However, here is a [tsconfig.json](https://github.com/benyap/benyap.com/blob/main/apps/web/tsconfig.json) in a monorepo I made a while back. Whilst the project doesn't use `resolve-tspaths`, it has a structure that would be well suited for it. I hope this can provide some insight into how you can adapt it for your use case.
