### ISSUE TITLE
Node.js v20 support

### ISSUE THREAD

**Issue by smartinio** [benyap/resolve-tspaths#334]
Hi, we're migrating our codebase from Node 18 to 20 and one of the challenges is that Node 20 needs explicit import specifiers. I'm shopping around for a build step that resolves all paths to their explicit paths including relative imports and node_module imports.

From what I can tell, this package does what I need but only for imports that go through the absolute `paths` in tsconfig. Any chance of this package expanding this to resolve relative + node_modules imports as well, including resolving folder imports to their index-file?

If not, do you know of any package that does this?

**Comment by benyap** [comment]
Hi @smartinio, thanks for the suggestion! I'm not aware of any packages that can do this.

And unfortunately I don't have the capacity to look into this currently. But it certainly does sound like a useful feature with the direction that Node is going in. If you have the time and interest, I would love for you to open a PR for this 😊

**Comment by smartinio** [comment]
Alright! For now [tsc-alias](https://www.npmjs.com/package/tsc-alias) seems to do the trick (with the `resolveFullPaths` option). Can circle back here if it doesn't work out
