### ISSUE TITLE
Import as a module

### ISSUE THREAD

**Issue by tcK1** [benyap/resolve-tspaths#57]
Hey! First of all, thanks for the package.

Just a suggestion/question: Would it make sense to have an export function that we could call programmatically?

For example, this is my use case: I'm using Esbuild to transpile my TS code, and just like `tsc` it doesn't "fix" the import paths (that's why I'm using this package! 😛 ) but what I **can** do with Esbuild, is adding hooks on the build steps, including an end hook. Here I can call `resolve-tspaths`.

```js
const resolveTsPathsPlugin = {
  name: 'resolve-tspaths',
  setup(build) {
    build.onEnd(result => {
      // `spawnSync` is used so we can be sure that the process is finished before we continue
      spawnSync('yarn', ['resolve-tspaths', '--out=dist'], {
        stdio: 'inherit',
      })
    })
  },
}

export const result = await build({
  outdir: 'dist',
  entryPoints: ['src/**/*.ts'],
  platform: 'node',
  plugins: [
    globPlugin(),
    resolveTsPathsPlugin
  ],
});
```

Instead of relying on the `spawnSync` node child process functionality, I could call the function here, for example:

```js
import { resolve } from 'resolve-tspaths';

const resolveTsPathsPlugin = {
  name: 'resolve-tspaths',
  setup(build) {
    build.onEnd(async result => {
	  await resolve({ out: 'dist' });
    })
  },
}
```

**Comment by benyap** [comment]
Hey @tcK1! Thanks for the suggestion. Definitely sounds like a good one - I'll look into this as soon as I have time!

**Comment by benyap** [comment]
@all-contributors please add @tcK1 for idea

**Comment by tcK1** [comment]
Amazing! Thank you so much.
